using DRModels
using Test
using LinearAlgebra
using TOML

# Contract for finite-state mean designs with complete exogenous factors.
#
# Native R's `model.matrix` applies treatment contrasts when a mean formula has
# an intercept. With `0 +`, the *first categorical term in formula order* is
# full rank, while every later categorical term uses its K - 1 treatment
# columns. The marked `mi(x)` variable is a categorical term for this purpose:
# its position relative to the fixed factors changes its rank. State-expanded
# rows must therefore be built from the complete state-specific mean formula;
# appending a fixed K- or K-1-column marker block is not sufficient. Interactions
# among complete, exogenous fixed factors retain the same native convention.
#
# This test deliberately excludes interactions containing `mi(x)`, missing
# fixed covariates, response/predictor reuse, random/structured effects, and
# non-Gaussian responses. Those remain existing explicit refusals.

function _finite_factor_data()
    n = 36
    levels = ["low", "medium", "high"]
    a = repeat(["a", "b", "c"], 12)
    b = repeat(["cold", "warm"], 18)
    z = collect(range(-1.0, 1.0; length = n))
    x = Union{Missing,String}[
        i in (5, 12, 19, 29) ? missing : levels[mod1(i, 3)] for i in 1:n
    ]
    y = 0.2 .+ 0.3 .* z .+ 0.1 .* (a .== "b") .- 0.15 .* (b .== "warm")
    flag = repeat([false, true], 18)
    return (; y, x, a, b, z, flag), levels
end

_finite_mi_columns(names) = findall(name -> occursin("mi(x)", name), names)

struct _FiniteOrderedLike
    value::String
end

function _finite_nonmarker_columns(names)
    setdiff(eachindex(names), _finite_mi_columns(names))
end

# Generated by native R's complete state-expanded `model.matrix` probe.  This
# guards against a same-width but different factor space in the Julia frontend.
const _finite_factor_reference = TOML.parsefile(joinpath(
    @__DIR__, "..", "docs", "dev-log", "evidence", "julia-r-parity",
    "finite-factor-coding", "native-design-001.toml"))
const _finite_bool_factor_reference = TOML.parsefile(joinpath(
    @__DIR__, "..", "docs", "dev-log", "evidence", "julia-r-parity",
    "finite-factor-coding", "native-design-002.toml"))

function _finite_factor_reference_state_design(reference, case)
    rows = reduce(vcat, [permutedims(Float64.(row)) for row in case["state_design"]])
    n = reference["n"]
    K = length(reference["levels"])
    p = size(rows, 2)
    @assert size(rows) == (n * K, p)
    state = Array{Float64}(undef, n, K, p)
    for i in 1:n, k in 1:K
        state[i, k, :] .= rows[(i - 1) * K + k, :]
    end
    return state
end

function _finite_factor_forms()
    return Dict(
        "intercept" => DRModels.bf(@formula(y ~ a + mi(x)), @formula(sigma ~ 1)),
        "factor_first" => DRModels.bf(@formula(y ~ 0 + a + b + mi(x)), @formula(sigma ~ 1)),
        "marker_first" => DRModels.bf(@formula(y ~ 0 + mi(x) + a + b), @formula(sigma ~ 1)),
        "numeric_before" => DRModels.bf(@formula(y ~ 0 + z + mi(x) + a), @formula(sigma ~ 1)),
        "interaction" => DRModels.bf(@formula(y ~ 0 + a * b + mi(x)), @formula(sigma ~ 1)),
        "interaction_marker_first" => DRModels.bf(@formula(y ~ 0 + mi(x) + a * b), @formula(sigma ~ 1)),
        "interaction_only_before" => DRModels.bf(@formula(y ~ 0 + a & b + mi(x)), @formula(sigma ~ 1)),
        "bool_first" => DRModels.bf(@formula(y ~ 0 + flag + mi(x)), @formula(sigma ~ 1)),
        "bool_marker_first" => DRModels.bf(@formula(y ~ 0 + mi(x) + flag), @formula(sigma ~ 1)),
        "bool_interaction" => DRModels.bf(@formula(y ~ 0 + flag * a + mi(x)), @formula(sigma ~ 1)),
    )
end

@testset "finite-state native factor coding contract" begin
    @test BLAS.get_num_threads() == 1
    @test isdefined(DRModels, :_joint_finite_native_state_design)

    data, levels = _finite_factor_data()
    @test String.(levels) == String.(_finite_factor_reference["levels"])
    @test String.(levels) == String.(_finite_bool_factor_reference["levels"])
    ordinal = DRModels.impute_model(@formula(x ~ 1);
        family = DRModels.CumulativeLogit(), levels = levels)
    categorical = DRModels.impute_model(@formula(x ~ 1);
        family = DRModels.CategoricalLogit(), levels = levels)
    ctl = DRModels.miss_control(response = "include", predictor = "model")

    # Intercept: both ordinary factor and marker use treatment contrasts.
    intercept = DRModels.bf(@formula(y ~ a + mi(x)), @formula(sigma ~ 1))
    Xi, ni = DRModels._joint_finite_native_state_design(intercept, data, :x, levels, :categorical)
    mi_i = _finite_mi_columns(ni)
    @test size(Xi) == (36, 3, 5) # intercept + a(B,C) + mi(medium,high)
    @test length(mi_i) == 2
    @test Xi[1, :, mi_i] == [0.0 0.0; 1.0 0.0; 0.0 1.0]

    # No intercept and factor before marker: a is full rank, mi(x) treatment.
    factor_first = DRModels.bf(@formula(y ~ 0 + a + b + mi(x)), @formula(sigma ~ 1))
    Xf, nf = DRModels._joint_finite_native_state_design(factor_first, data, :x, levels, :categorical)
    mi_f = _finite_mi_columns(nf)
    fixed_f = _finite_nonmarker_columns(nf)
    @test size(Xf) == (36, 3, 6) # a(3) + b(1) + mi(2)
    @test length(mi_f) == 2
    @test Xf[1, :, mi_f] == [0.0 0.0; 1.0 0.0; 0.0 1.0]
    @test Xf[:, 1, fixed_f] == Xf[:, 2, fixed_f]
    @test Xf[:, 2, fixed_f] == Xf[:, 3, fixed_f]

    # No intercept and marker first: mi(x) is the full-rank first factor.
    marker_first = DRModels.bf(@formula(y ~ 0 + mi(x) + a + b), @formula(sigma ~ 1))
    Xm, nm = DRModels._joint_finite_native_state_design(marker_first, data, :x, levels, :categorical)
    mi_m = _finite_mi_columns(nm)
    fixed_m = _finite_nonmarker_columns(nm)
    @test size(Xm) == (36, 3, 6) # mi(3) + a(2) + b(1)
    @test length(mi_m) == 3
    @test Xm[1, :, mi_m] == Matrix{Float64}(I, 3, 3)
    @test Xm[:, 1, fixed_m] == Xm[:, 2, fixed_m]
    @test Xm[:, 2, fixed_m] == Xm[:, 3, fixed_m]

    # A numeric covariate does not consume the first-factor full-rank role.
    numeric_before = DRModels.bf(@formula(y ~ 0 + z + mi(x) + a), @formula(sigma ~ 1))
    Xz, nz = DRModels._joint_finite_native_state_design(numeric_before, data, :x, levels, :categorical)
    @test size(Xz) == (36, 3, 6) # z + mi(3) + a(2)
    @test length(_finite_mi_columns(nz)) == 3

    # Fixed-factor interactions are retained and remain state invariant.
    interaction = DRModels.bf(@formula(y ~ 0 + a * b + mi(x)), @formula(sigma ~ 1))
    Xab, nab = DRModels._joint_finite_native_state_design(interaction, data, :x, levels, :categorical)
    fixed_ab = _finite_nonmarker_columns(nab)
    @test size(Xab) == (36, 3, 8) # a(3) + b(1) + mi(2) + a:b(2)
    @test length(_finite_mi_columns(nab)) == 2
    @test Xab[:, 1, fixed_ab] == Xab[:, 2, fixed_ab]
    @test Xab[:, 2, fixed_ab] == Xab[:, 3, fixed_ab]

    # Ordered predictors use their existing polynomial state contrasts under an
    # intercept, but respect first-factor full coding without one.
    Xo, no = DRModels._joint_finite_native_state_design(intercept, data, :x, levels, :ordinal)
    mi_o = _finite_mi_columns(no)
    @test size(Xo) == (36, 3, 5)
    @test no[mi_o] == ["mi(x).L", "mi(x).Q"]
    @test Xo[1, :, mi_o] ≈ DRModels._joint_finite_polynomials(3) atol = 2e-14
    Xof, nof = DRModels._joint_finite_native_state_design(factor_first, data, :x, levels, :ordinal)
    mi_of = _finite_mi_columns(nof)
    @test size(Xof) == (36, 3, 6)
    @test nof[mi_of] == ["mi(x).L", "mi(x).Q"]
    @test Xof[1, :, mi_of] ≈ DRModels._joint_finite_polynomials(3) atol = 2e-14
    Xon, non = DRModels._joint_finite_native_state_design(marker_first, data, :x, levels, :ordinal)
    mi_on = _finite_mi_columns(non)
    @test size(Xon) == (36, 3, 6)
    @test Xon[1, :, mi_on] == Matrix{Float64}(I, 3, 3)

    # The native fixture records every row/state/column value and generated
    # name for all admitted formula positions.  Fixture 002 supersedes the
    # original 14 cases with three Boolean-factor cases per finite family.
    # This is deliberately stronger than checking only rank or hand-derived
    # widths: it proves that Bool is factor-coded as FALSE/TRUE, while `z`
    # remains an ordinary numeric covariate.
    @test Set(keys(_finite_factor_forms())) == Set(keys(_finite_bool_factor_reference["ordinal"]))
    for predictor in (:ordinal, :categorical)
        fixtures = _finite_bool_factor_reference[string(predictor)]
        for (id, form) in _finite_factor_forms()
            reference = fixtures[id]
            @test reference["model_matrix_error"] == 0
            actual, names = DRModels._joint_finite_native_state_design(form, data, :x, levels, predictor)
            @test names == String.(reference["mu_names"])
            @test actual ≈ _finite_factor_reference_state_design(_finite_bool_factor_reference, reference) atol = 2e-14 rtol = 0
        end
    end

    # Colons and ampersands are valid parts of a factor level.  Native names
    # concatenate each structured variable/level component and only then join
    # interaction components with `:`; normalizing rendered StatsModels text
    # would corrupt these labels.
    punctuation = (
        y = zeros(6),
        x = Union{Missing,String}[missing for _ in 1:6],
        a = repeat(["base", "level & dry", "level: wet"], 2),
        b = repeat(["b & high", "b: base"], inner = 3),
    )
    punctuation_form = DRModels.bf(@formula(y ~ a * b + mi(x)), @formula(sigma ~ 1))
    _, punctuation_names = DRModels._joint_finite_native_state_design(
        punctuation_form, punctuation, :x, levels, :categorical)
    @test punctuation_names == [
        "(Intercept)", "alevel & dry", "alevel: wet", "bb: base",
        "mi(x)medium", "mi(x)high", "alevel & dry:bb: base", "alevel: wet:bb: base",
    ]

    # Formula admission must use the same construction, not a separate branch.
    bool_first = DRModels.bf(@formula(y ~ 0 + flag + mi(x)), @formula(sigma ~ 1))
    Xbool, nbool = DRModels._joint_finite_native_state_design(bool_first, data, :x, levels, :categorical)
    @test nbool == ["flagFALSE", "flagTRUE", "mi(x)medium", "mi(x)high"]
    categorical_fit = drm(factor_first, DRModels.Gaussian(); data = data,
        impute = (x = categorical,), missing = ctl, g_tol = 1e-8)
    @test categorical_fit isa DRModels.JointFiniteDrmFit
    @test categorical_fit.prepared.prepared.X_mu_state ≈ Xf atol = 2e-14
    ordinal_fit = drm(marker_first, DRModels.Gaussian(); data = data,
        impute = (x = ordinal,), missing = ctl, g_tol = 1e-8)
    @test ordinal_fit isa DRModels.JointFiniteDrmFit
    @test ordinal_fit.prepared.prepared.X_mu_state ≈ Xon atol = 2e-14
    bool_fit = drm(bool_first, DRModels.Gaussian(); data = data,
        impute = (x = categorical,), missing = ctl, g_tol = 1e-8)
    @test bool_fit isa DRModels.JointFiniteDrmFit
    @test bool_fit.prepared.prepared.X_mu_state ≈ Xbool atol = 2e-14

    # Native R retains both logical levels even in an all-FALSE data slice;
    # the TRUE full-rank column is therefore deliberately all zero.
    one_level_bool = merge(data, (; flag = fill(false, 36)))
    Xfalse, nfalse = DRModels._joint_finite_native_state_design(
        bool_first, one_level_bool, :x, levels, :categorical)
    @test size(Xfalse) == (36, 3, 4)
    @test nfalse == ["flagFALSE", "flagTRUE", "mi(x)medium", "mi(x)high"]
    @test all(@view(Xfalse[:, :, 1]) .== 1.0)
    @test all(@view(Xfalse[:, :, 2]) .== 0.0)
    @test Xfalse[1, :, 3:4] == [0.0 0.0; 1.0 0.0; 0.0 1.0]

    # A package-specific ordered/categorical value is not silently reduced to
    # an arbitrary treatment dummy.  It needs a typed contrast contract, which
    # this frontend deliberately does not import from optional packages.
    ordered_data = merge(data, (; ordered = [_FiniteOrderedLike(levels[mod1(i, 3)]) for i in 1:36]))
    # The same values in an unrelated column cannot narrow an otherwise
    # admitted design: the guard inspects formula-used columns only.
    unrelated_X, unrelated_names = DRModels._joint_finite_native_state_design(
        factor_first, ordered_data, :x, levels, :categorical)
    @test unrelated_names == nf
    @test unrelated_X ≈ Xf atol = 2e-14 rtol = 0
    ordered_form = DRModels.bf(@formula(y ~ 0 + ordered + mi(x)), @formula(sigma ~ 1))
    ordered_error = try
        drm(ordered_form, DRModels.Gaussian(); data = ordered_data,
            impute = (x = categorical,), missing = ctl, g_tol = 1e-8)
        nothing
    catch error
        error
    end
    @test ordered_error isa ArgumentError
    @test occursin("typed contrast contract", sprint(showerror, ordered_error))
end

println("FINITE_JOINT_FACTOR_CODING_TEST_READY")
