# test_bridge_silent_sweep.jl — sweep of the remaining formula constructs
# named in the #467 follow-up brief for the bug class "an R formula
# construct passes through the bridge's translation and runs, but means
# something different in Julia".
#
# Method: run each construct through `drm_bridge`'s formula translation and
# classify it FAITHFUL / SHARP-REFUSAL / LATE-ERROR / SILENTLY-WRONG by
# comparing against base R's own `stats::model.matrix()` on byte-identical
# data (fixtures under test/fixtures/bridge_silent_sweep/, generated by
# gen.R). Every LATE-ERROR found in this sweep (a bare Julia parse error, an
# `UndefVarError` deep in the model frame, or a scalar-label renderer
# crashing on a foreign argument grammar — none of which name the actual
# unsupported R construct) is converted here into a SHARP-REFUSAL that names
# the construct explicitly. No SILENTLY-WRONG construct was found in this
# sweep (see the PR description's classification table for the full list,
# including the constructs that were already FAITHFUL or already a clean
# SHARP-REFUSAL and so needed no change).
#
#   julia --project=. -e 'using DRModels, Test; include("test/test_bridge_silent_sweep.jl")'

module TestBridgeSilentSweep

using DRModels
using Test
using DelimitedFiles: readdlm
using LinearAlgebra: \

const FIXTURE = joinpath(@__DIR__, "fixtures", "bridge_silent_sweep")

function _load_csv(path)
    raw, header = readdlm(path, ','; header = true)
    cols = Symbol.(strip.(string.(vec(header))))
    return cols, raw
end

function _load_data()
    cols, raw = _load_csv(joinpath(FIXTURE, "data.csv"))
    numeric = Set((:x, :z, :h, :y))
    pairs = map(enumerate(cols)) do (j, name)
        col = raw[:, j]
        if name in numeric
            name => Float64[parse(Float64, string(v)) for v in col]
        else
            name => string.(strip.(string.(col)))
        end
    end
    return NamedTuple(pairs)
end

# R's own `model.matrix()` output for one construct: column names (R
# spelling, unprefixed) and the numeric design matrix itself.
function _oracle_matrix(slug)
    cols, raw = _load_csv(joinpath(FIXTURE, slug * ".csv"))
    names = String.(cols)
    values = Float64[parse(Float64, string(v)) for v in raw]
    return names, reshape(values, size(raw))
end

const _DATA = _load_data()
const _Y = _DATA.y

# Ordinary-least-squares solve against R's OWN design matrix: for the
# Gaussian identity-link mean this is the exact MLE, so comparing it to the
# bridge's fitted `mu_*` coefficients checks the ACTUAL VALUES the bridge
# put into its design matrix (not merely the column names) against R's
# `model.matrix()`, without needing to expose the bridge's internal matrix.
function _oracle_ols(slug)
    _, X = _oracle_matrix(slug)
    beta = X \ _Y
    return vec(beta)
end

function _mu_coefs(out)
    idx = findall(n -> startswith(n, "mu_"), out["coef_names"])
    return out["coefficients"][idx]
end

@testset "bridge silent-formula sweep (#467 follow-up)" begin
    @testset "FAITHFUL: names and fitted values match R model.matrix()" begin
        cases = [
            ("y ~ x - 1", "x_minus1"),
            ("y ~ 0 + x", "zero_plus_x"),
            ("y ~ x + z - z", "x_plus_z_minus_z"),
            ("y ~ log(x+3)", "log_x"),
            ("y ~ x^2", "x_sq"),
            ("y ~ (x + z)^2 - x:z", "cross_sq_minus"),
            ("y ~ x:f", "x_colon_f"),
            ("y ~ f - 1", "f_minus1"),
        ]
        for (formula, slug) in cases
            @testset "$formula" begin
                exp_names, _ = _oracle_matrix(slug)
                out = DRModels.drm_bridge(; formula = formula, family = "gaussian", data = _DATA)
                mu_names = [n for n in out["coef_names"] if startswith(n, "mu_")]
                @test mu_names == ["mu_" * n for n in exp_names]
                @test _mu_coefs(out) ≈ _oracle_ols(slug) atol = 1e-6
            end
        end
    end

    @testset "SHARP-REFUSAL: was LATE-ERROR before this sweep" begin
        cases = [
            ("y ~ .", "dot", "every other column"),
            ("y ~ splines::ns(x, 3)", "pkg::fn", "package-qualified"),
            ("y ~ cut(x, 3)", "cut", "cut"),
            ("y ~ interaction(f, g)", "interaction", "interaction"),
            ("y ~ offset(x) + x", "offset", "offset"),
            ("y ~ C(g, contr.sum)", "C", "contrast"),
        ]
        for (formula, slug, needle) in cases
            @testset "$slug" begin
                err = try
                    DRModels.drm_bridge(; formula = formula, family = "gaussian", data = _DATA)
                    nothing
                catch e
                    e
                end
                @test err isa ArgumentError
                msg = sprint(showerror, err)
                @test occursin(needle, msg)
                @test occursin("engine=\"julia\"", msg)
            end
        end
    end

    @testset "SHARP-REFUSAL: already correct before this sweep (regression guard)" begin
        # `x * z - x:z` refuses (rather than silently mis-computing) because
        # the `-` term-removal algebra does not expand an unflattened `*`
        # crossing first; R itself reduces this to `x + z`, so the refusal is
        # conservative, not a defect (#467 sweep finding).
        err = try
            DRModels.drm_bridge(; formula = "y ~ x * z - x:z", family = "gaussian", data = _DATA)
            nothing
        catch e
            e
        end
        @test err isa ArgumentError
        @test occursin("unexpanded `*` crossing", sprint(showerror, err))

        # `poly(x, 2, raw = TRUE)` refuses: R's `raw = TRUE` basis is not the
        # orthogonal basis this bridge reproduces to machine precision.
        err2 = try
            DRModels.drm_bridge(; formula = "y ~ poly(x, 2, raw = TRUE)", family = "gaussian", data = _DATA)
            nothing
        catch e
            e
        end
        @test err2 isa ArgumentError
        @test occursin("raw = TRUE", sprint(showerror, err2))

        # `as.numeric(f)` (a dotted R function name with no Julia call
        # target) already names the unsupported function cleanly.
        err3 = try
            DRModels.drm_bridge(; formula = "y ~ as.numeric(factor(f))", family = "gaussian", data = _DATA)
            nothing
        catch e
            e
        end
        @test err3 isa ArgumentError
        @test occursin("as.numeric", sprint(showerror, err3))
    end
end

println("BRIDGE_SILENT_SWEEP_DONE")

end # module
